name: .NET WebAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.403'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build --no-restore --configuration Release
        working-directory: ./api

